version: '3.8'

services:
  database:
    image: postgres:17.2
    restart: always
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - /tmp/database:/var/lib/postgresql/data
  